# Generated by Django 2.2.6 on 2019-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_pontosturisticos_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
