# Generated by Django 2.2.6 on 2019-11-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontosturisticos_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturisticos',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
